#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# build worker image (VM template)
image: Visual Studio 2017

# environment variables
environment:
  NUGET_API_KEY:
    secure: yMSTosOd+md735zBxHpaCUk5BmPL0MEpjNMwWNJklXYDHzOPpaXjIKBcqpDp5RtF

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: ./build/build.ps1

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: artifacts/*.nupkg
